---
# Calamares main configuration for arch-javid installer

modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - locale
      - keyboard
      - localecfg
      - fstab
      - shellprocess@mkinitcpio
      - users
      - networkcfg
      - displaymanager
      - hwclock
      - packages
      - bootloader
      - services-systemd
      - umount
  - show:
      - finished

branding: arch-javid

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
