---
# Bootloader configuration

efiBootLoader: "systemd-boot"

# Kernel / initramfs paths (relative to the EFI partition root).
# These are needed for systemd-boot to create correct loader entries.
kernel:   "/vmlinuz-linux"
img:      "/initramfs-linux.img"
fallback: "/initramfs-linux-fallback.img"

# Main loader.conf options
timeout:  5
kernelLine: default

kernelParams: [ "quiet", "nowatchdog" ]
