---
# fstab options
mountOptions:
    - filesystem: default
      options:    defaults,noatime
    - filesystem: btrfs
      options:    defaults,noatime,compress=zstd

# Write a swapfile entry if a swapfile is used
swapon: true

# EFI mount point written to fstab
efiMountPoint: /boot
