---
# fstab options
mountOptions:
  - filesystem: default
    options:    defaults,noatime
  - filesystem: btrfs
    options:    defaults,noatime,compress=zstd

# EFI mount point written to fstab
efiMountPoint: /boot
