---
# Configuration for the initcpiocfg module, which generates an initramfs configuration file in the target system.

useSystemdHook: true
hooks:
    prepend: [ bogus ]
    append: [ bogus ]
    remove: [ bogus ]

source: "/etc/mkinitcpio.conf"
