---
# Write an X11 keyboard config to the target system
keyboardOptionsModel: "pc105"

# X11 keyboard defaults (the keyboard page lets the user change these)
xOrgConfFileName: "/etc/X11/xorg.conf.d/00-keyboard.conf"

# Write a vconsole.conf for the virtual console keymap
vconsoleConfFileName: "/etc/vconsole.conf"
