---
# Mount module configuration

extraMounts:
    - device: proc
      fs: proc
      mountPoint: /proc
    - device: sys
      fs: sysfs
      mountPoint: /sys
    - device: /dev
      mountPoint: /dev
      options: [ bind ]
    - device: tmpfs
      fs: tmpfs
      mountPoint: /run
    - device: /run/udev
      mountPoint: /run/udev
      options: [ bind ]
    - device: efivarfs
      fs: efivarfs
      mountPoint: /sys/firmware/efi/efivars
      efi: true

btrfsSubvolumes:
    - mountPoint: /
      subvolume: /@
    - mountPoint: /home
      subvolume: /@home
    - mountPoint: /root
      subvolume: /@root
    - mountPoint: /srv
      subvolume: /@srv
    - mountPoint: /var/cache
      subvolume: /@cache
    - mountPoint: /var/tmp
      subvolume: /@tmp
    - mountPoint: /var/log
      subvolume: /@log

mountOptions:
    - filesystem: default
      options: [ defaults, noatime ]
    - filesystem: btrfs
      hddOptions: [ compress=zstd ]
      ssdOptions: [ compress=zstd ]
      nvmeOptions: [ compress=zstd:1 ]
      options: [ defaults, noatime ]
    - filesystem: ext4
      options: [ defaults, noatime ]
