---
efiSystemPartition:     "/boot"
efiSystemPartitionName: "EFI"
efiSystemPartitionSize: "2048MiB"

# Remove swap from the UI: matches the no-swap design decision in this project
userSwapChoices:
  - none

initialPartitioningChoice: erase
initialSwapChoice: none

defaultFileSystemType: "btrfs"
availableFileSystemTypes:
  - btrfs
  - ext4
