---
# Calamares partition module configuration

# Backend: uses kpmcore
backend: kpmcore

# EFI system partition mount point
efiSystemPartition:     "/boot"
efiSystemPartitionSize: 2048M
efiSystemPartitionName: BOOT

userSwapChoices:
    - none

drawNestedPartitions:   false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none

defaultFileSystemType:  "btrfs"
defaultPartitionTableType: gpt

availableFileSystemTypes:  ["btrfs","ext4"]
