---
# The displaymanager module does not support plasmalogin.
# NetworkManager and plasmalogin are enabled here instead.
services:
  - name: NetworkManager
    mandatory: true
  - name: plasmalogin
    mandatory: true
