---
# systemd services to enable/disable in the installed system

units:
  - name: "NetworkManager"
    action: "enable"

  - name: "systemd-timesyncd"
    action: "enable"

  - name: "firewalld"
    action: "enable"

  - name: "sddm"
    action: "enable"

  - name: "fstrim.timer"
    action: "enable"

  - name: "bluetooth"
    action: "enable"

  - name: "arch-update.timer"
    action: "enable"
    user: true

  - name: "arch-update-tray.service"
    action: "enable"
    user: true
