---
userShell: /bin/bash

defaultGroups:
  - users
  - lp
  - video
  - network
  - storage
  - wheel
  - audio

sudoersGroup:    wheel
setRootPassword: true

availableShells:
  - /bin/bash
  - /bin/zsh

autologinGroup: autologin
