---
# Users module — creates the main user account

userShell: /bin/bash

defaultGroups:
  - wheel
  - rfkill
  - sys
  - lp
  - video
  - network
  - storage
  - audio

doAutoLogin: false
sudoersGroup: wheel

setRootPassword: true
doReusePassword: true

allowWeakPasswords: false
allowWeakPasswordsDefault: false
