---
showSupportUrl: false
showKnowledgeBaseUrl: false
showReleaseNotesUrl: false

requirements:
  requiredStorage:  20
  requiredRam:      2.0
  checkBattery:     false
  checkInternet:    true
  checkRoot:        true
  checkScreen:      false
