name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Cache pacman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: archlinux-pacman-${{ hashFiles('.github/workflows/build.yml') }}
          restore-keys: |
            archlinux-pacman-
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm archiso
      - name: Copy Releng profile
        run: |
          cp -r /usr/share/archiso/configs/releng/ /root/${{ github.event.repository.name }}
      - name: Prepare build directory
        run: |
          # Copy files to build directory
          cp $GITHUB_WORKSPACE/profiledef.sh .
          cp $GITHUB_WORKSPACE/packages.x86_64 .
          cp $GITHUB_WORKSPACE/packages.txt airootfs/root/

          cp -r $GITHUB_WORKSPACE/airootfs/* airootfs/
          chmod +x airootfs/root/customize_airootfs.sh

          cp -r $GITHUB_WORKSPACE/scripts airootfs/root/

          chown root:root airootfs/root/packages.txt
          chown root:root airootfs/root/customize_airootfs.sh
          chown root:root airootfs/etc/sddm.conf.d/autologin.conf
          chown root:root airootfs/etc/sudoers.d/liveuser
        working-directory: /root/${{ github.event.repository.name }}
      - name: Build ISO
        run: |
          mkarchiso -v -w /root/work -o /root/out .
        working-directory: /root/${{ github.event.repository.name }}
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-iso
          path: /root/out/*.iso
